sonar.projectKey=soat-11_soat-production
sonar.organization=soat-11

# Caminho para o código fonte
sonar.sources=src
sonar.tests=test
sonar.language=ts
sonar.sourceEncoding=UTF-8

# Exclusões (Arquivos que não contam para cobertura)
# Deve ser igual ao que fizemos no package.json/jest
sonar.exclusions=**/*.module.ts, **/*.dto.ts, **/*.entity.ts, **/*.enum.ts, **/*.interface.ts, src/main.ts, dist/**, coverage/**, **/*.spec.ts, **/*.steps.ts, **/*.test.ts, **/*.js

# Caminho do relatório de cobertura gerado pelo Jest
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.coverage.exclusions=**/*.module.ts, **/*.dto.ts, **/*.entity.ts, **/*.enum.ts, **/*.interface.ts, src/main.ts, test/**, src/infra/database/migrations/**, **/*.spec.ts, **/*.steps.ts