name: SonarQube Quality Check

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]

jobs:
  sonarcloud:
    name: SonarCloud Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Instalar dependências
        run: npm ci

      - name: Rodar Testes e Gerar Coverage
        run: npm run test:cov
        env:
          PORT: 3001
          NODE_ENV: test
          MONGO_URI: mongodb://localhost:27017/production_db_test
          CART_SERVICE_URL: http://localhost:3000
          AWS_REGION: us-east-1
          SQS_ENDPOINT: http://localhost:4566
          AWS_ACCESS_KEY_ID: fake
          AWS_SECRET_ACCESS_KEY: fake
          SQS_PAYMENT_CONFIRMED_URL: https://sqs.fake/payment-confirmed
          SQS_PRODUCTION_STARTED_URL: https://sqs.fake/production-started
          SQS_PRODUCTION_READY_URL: https://sqs.fake/production-ready
          SQS_PRODUCTION_WITHDRAWN_URL: https://sqs.fake/production-withdrawn

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
